[db]
host = "localhost"
port = "5433"
user = "lab2user"
pass = "lab2pass"
name = "lab2db"
sslmode = "disable"

[jwt]
secret = "my-secret-key-for-jwt-tokens"
expires_in = 86400
signing_method = "HS256"

[redis]
host = "localhost"
port = 6379
password = "password"
dial_timeout = 10
read_timeout = 10

